### ISSUE TITLE
Are there plans to include a format date helper?

### ISSUE THREAD

**Issue by fakenickels** [mobily/re-date#3]
I could not found it 🤔
If you guys have a WIP there for it I'll await, if no we can maybe enable some ideas in this thread for how to implement in Reason

**Comment by mobily** [comment]
Hello @grsabreu, personally, I prefer to use the `Intl` API. It's supported by all modern browsers and I believe it's more accurate in formatting dates. I'm fully convinced this approach is simply better in multilingual projects.

However, it doesn't mean that we don't want `format` in `re-date` :) If you had a few moments to post your ideas on how to implement this, that would be great.

Useful links:
https://caniuse.com/#search=intl
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl

**Comment by fakenickels** [comment]
What do you think towards including https://github.com/andyearnshaw/Intl.js and offering bindings to it through re-date?

**Comment by ashton** [comment]
Hi, any news on this? I think this lib is much more elegant that any other that I'm using, but not having format is kinda bummer since it's probably the most used functionality (along with parse) when using a date lib
